version: '3'

services:
  postgres:
    image: postgres:10.7
    restart: always
    privileged: false
    build:
      dockerfile: postgres.Dockerfile
      context: ./
    expose: ["5432"]
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  # this is mlflow batch run service
  mlflow-tracking-server:
    image: mlflow-tracking-server
    restart: always
    privileged: false
    build:
      dockerfile: mlflow.Dockerfile
      context: ./
      args:
      - MY_ENV=production
    ports:
      - "5000:5000"
    volumes:
      - /Users:/Users
    environment:
      POSTGRES_HOST : postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      ARTIFACT_ROOT: ${ARTIFACT_ROOT}
